### ISSUE TITLE
Editor crashing after I download WordPress using WordPress Suite > Setup > Download WordPress

### ISSUE THREAD

**Issue by pstonier** [peterjohnhunt/wordpress-suite#11]
Any project that I've done this. The editor freezes and then crashes even after it's done downloading WordPress.

**Comment by peterjohnhunt** [comment]
hi @pstonier! Thanks for using Wordpress Suite and taking the time to submit this bug!

I'm not initially able to replicate that issue on my machine, so i'd like to learn as much about your environment and hopefully we can get it ironed out as quick as possible!

What OS, and Atom version are you running?

Are you able to use wp-cli to download Wordpress through the command line?

**Comment by pstonier** [comment]
OS X 10.12.5
Atom 1.18.0

Yes, I can use wp-cli and download WordPress.

The files download just fine through the WordPress Suite, too and the notifications show up saying that its downloading via WP-CLI, but it seems like some kind of watch process is getting stuck and freezing everything.

**Comment by peterjohnhunt** [comment]
Thanks for the additional details!

After the window freezes, if you restart Atom and add that project (which now has the downloaded Wordpress). Does it freeze again? Or only on the actual download?

Another question, could you do the following:

open wordpress-suite package settings and change debug level to 10
install https://atom.io/packages/debug-service
restart atom
open the inspector (CMD+ALT+I)
attempt to download Wordpress core
send me the log messages from the console (removing any personal info)

Thanks a ton!

**Comment by pstonier** [comment]
There were no log messages, but I have narrowed down the problem to another add-on… the core package of atom-github. With that disabled. Everything works fine. Thanks for the help!

**Comment by peterjohnhunt** [comment]
Thanks for the info @pstonier. I've been testing around, and even with wordpress-suite disabled, the atom-github package (which is new to version 1.18.0) is making my Atom run extremely slow and crash. Disabling that package resolves that for me. My guess is there is a bug in that package unrelated to wordpress-suite, so I may wait a bit for a patch release from github before doing any more digging.

**Comment by peterjohnhunt** [comment]
Going to close this for now. Feel free to reopen if the issue reoccurs unrelated to github package!
