### ISSUE TITLE
Configuration to turn off notifications and debug log when opening a project

### ISSUE THREAD

**Issue by carl-alberto** [peterjohnhunt/wordpress-suite#13]
By default, notifications and debug log is on, this causes Atom to load slow especially if you have accumulated bit log file. Hopefully we can add an option to turn off notifications and debug log when opening a project.

**Comment by peterjohnhunt** [comment]
Good thought! I'll see about adding some settings options for this!

**Comment by carl-alberto** [comment]
thanks @peterjohnhunt, excellent tool you got here and I'm really lovin Atom plus this package. I'll try to also open a PR whenever I can :)

**Comment by peterjohnhunt** [comment]
Thanks @carl-alberto! Been a little slammed with my day job, but hoping to get an initial implementation of this sometime this week or so!

**Comment by peterjohnhunt** [comment]
@carl-alberto I have added some initial / simple new settings options in [v1.2.1](https://github.com/peterjohnhunt/wordpress-suite/releases/tag/v1.2.1)

Let me know what you think!

**Comment by carl-alberto** [comment]
Nice! Thanks for the update :)
