### ISSUE TITLE
SyntaxError: Unexpected end of input - commands.js:13:19

### ISSUE THREAD

**Issue by learning2** [peterjohnhunt/wordpress-suite#2]
I am getting this error after installing wp-cli manually. I'm a newbie with Atom and this type of environment. I did get the path to php finally :)

[Error WordPress-Suite 10 03 16.txt](https://github.com/peterjohnhunt/wordpress-suite/files/507408/Error.WordPress-Suite.10.03.16.txt)

**Comment by peterjohnhunt** [comment]
Thanks for submitting this! Are you able to use WPCLI via the command line without any issues?
