### ISSUE TITLE
Ability to set --path in wp-cli.yml or some other settings file

### ISSUE THREAD

**Issue by Gaffen** [peterjohnhunt/wordpress-suite#3]
Hi there, I've been encountering a bug when wordpress is installed in a subdirectory rather than root.

For example, my project is `hp-api`, my wordpress root is `hp-api/wp`, and my `wp-content` folder is in `hp-api/wp-content`

I've set up a `wp-cli.yml`, which has allowed me to run wp-cli from the command line, but `wordpress-suite` gives me the following error on startup

```
Error: Command failed: wp option get blogname --format="json" --path="/Applications/XAMPP/xamppfiles/htdocs/hp_api"
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
```

Is there a way to set the --path option appropriately for this? The strangest thing is the package is working on my work computer but not an my home machine, but I can't think of what might be causing it to work in the other computer. By all means it shouldn't be, just one morning it started working for reasons I can't fathom; and ever since I've been hooked so I'd love to get it working elsewhere!

**Comment by peterjohnhunt** [comment]
Hi @Gaffen,

I'll definitely take a look. is the custom wp-cli.yml in the `hp-api/` folder? Or is it a global config?

Would you be able to send me the contents of your `wp-cli.yml` so I can do some tests on my side?

**Comment by Gaffen** [comment]
Hi @peterjohnhunt,

Yes, the `wp-cli.yml` is in the `hp-api/` folder.

The content of the file is simply `path: wp`, though I have also tried variations of `./wp`, `/wp`, `wp/`, etc.

Thanks for this, let me know if you need further information!

**Comment by peterjohnhunt** [comment]
Hi @Gaffen,

This has been added in [v0.4.0](https://github.com/peterjohnhunt/wordpress-suite/releases/tag/v0.4.0).

It will auto check for a wp-cli.yml in the root folder, and then will use the path inside of that for the wpcli integration.

I'm going to close this, but feel free to reopen it if you run into any issues with the additions!

Thanks for using Wordpress Suite!

**Comment by Gaffen** [comment]
Hi @peterjohnhunt, I'm back to pester you again 😅

So I had *another* setup optimisation, and now my wp-content folder and wordpress folder aren't in the root of my project. At the moment I'm fixing this by manually setting the debug.log directory to be in project root, but ideally there would be some way of telling your plugin to look in the `WP_CONTENT_DIR`. No worries if this isn't on your roadmap but I wanted to let you know about this use case 👍

Thanks again for your work on this plugin; I really love it as a tool - makes me feel like I'm using an IDE!

**Comment by peterjohnhunt** [comment]
@Gaffen 

Hmm,

I should be able to add something in for that in the new version which primarily uses WP-CLI to get the paths, only using the defaults if necessary. I will add it to my list for version 2.0.

2.0 is nearly ready, unfortunately I'm delayed by trying to fix a bug that atom is presenting me. Once i have that patched up, i'll release 2.0 and try and implement a addition for your request!

Thanks for tracking issues and ideas, and glad you like it!

Created a separate issue for this: [#6](https://github.com/peterjohnhunt/wordpress-suite/issues/6)

**Comment by peterjohnhunt** [comment]
@Gaffen,

Would you be able to do the following as a beta test?

1) Remove wordpress-suite from Atom
2) Clone this repo locally: https://github.com/peterjohnhunt/wordpress-suite.git
3) `cd wordpress-suite` then `git checkout refactor` and run `apm install` followed by `apm link`
4) Reload Atom

This will get you on version 2 where i have added a feature to check for the WP_CONTENT_DIR. Version 2 overall might be a bit buggy here and there as a forewarning!

Thanks a ton!

**Comment by Gaffen** [comment]
@peterjohnhunt oh my, sorry I missed this - I will do it tonight!

**Comment by Gaffen** [comment]
@peterjohnhunt I'm afraid that at the moment, although it *is* reading debug.log, it's only loading it on initialisation and not logging any further ones. The log also comes up as a wp-cli error, and there is no option to clear the log

**Comment by peterjohnhunt** [comment]
Would you mind pasting the wp-cli error?

**Comment by Gaffen** [comment]
It's literally the string that I logged from PHP:
```
andreacremonini | WP-CLI Error
test
```

**Comment by Gaffen** [comment]
If you require any further information from my side just let me know!

**Comment by peterjohnhunt** [comment]
Will do! Sorry I have yet to get around to working on it! My work load has been quite busy! Hoping to get back to it soon!

**Comment by peterjohnhunt** [comment]
@Gaffen, haven't forgotten about this. sorry for the delay though. Should have some progress made on it shortly with a fix pushed up. I think i know where the error is occurring, just gotta patch it up.

**Comment by Gaffen** [comment]
Hi @peterjohnhunt; I just started up my editor today and the issue appears to be solved - have you made changes? I'll keep watching out to see if anything has changed on my end but I'll keep you updated.

**Comment by peterjohnhunt** [comment]
That's good news! Any thing you know of that changed?

**Comment by Gaffen** [comment]
My apologies, I meant to get back to you earlier. As far as I can see nothing has changed. Maybe an update to the plugin fixed it? As far as I can tell it works again now, but I shall get in touch if I encounter it again, if that's ok - as I can't 100% for certain say it's fixed until I work on the project that required this again.

**Comment by Gaffen** [comment]
Ugh, my bad @peterjohnhunt, looks like it was just that I was working on an old project - I tried testing this with my current setup again last night and it wasn't working. I'm happy to provide any help you might need to set this up!

**Comment by peterjohnhunt** [comment]
Hey @Gaffen, thanks for the info. Due to the Atom updating treeview / docks, i'm doing some rework anyways and adding some more rigorous logging to help in the additional support and features like this one. As always, it's all an after hours endeavor and I want to get it fixed up as soon as possible, but might take a tad longer than i usually hope. Thanks for your patience and continued investment in reporting and helping with these issues / features!

**Comment by Gaffen** [comment]
No worries at all, if there's anything I can do to help let me know!

**Comment by peterjohnhunt** [comment]
alrighty, just finished up a complete overhaul (again) of Wordpress Suite! It's way less buggy and should be just about ready to release. For the WP_CONTENT_DIR issue, what would you think about putting a line in your WPCLI YML called `content: path/to/content/dir` or something like that? i could pretty easily read that, which might be simpler than trying to dynamically get the WP_CONTENT_DIR variable value from wordpress itself.

**Comment by peterjohnhunt** [comment]
@Gaffen, I might actually try and go a slightly different route on this. Any chance you could send me a bare bones version of the environment you've been working on? A zip of a wordpress site and database with the config options set (including wp-cli.yml, etc) would be perfect!

**Comment by Gaffen** [comment]
Apologies peter, I've been a bit swamped recently - I will send you a working copy of my setup soon! Is the email listed on your github profile the most appropriate place to send it?

**Comment by peterjohnhunt** [comment]
yes, that email works great! thanks @Gaffen! Also, if you are still using the beta version, i would recommend deleting it and downloading through atom the newest version which is much improved!

**Comment by peterjohnhunt** [comment]
hey @Gaffen still interested in adding this feature once you're ready! No rush! Just reopen this ticket or email me the zip of files / db to test with and i should be able to get it added in quickly!
