### ISSUE TITLE
Please rename `initialize` method on main module to avoid breaking in Atom 1.14

### ISSUE THREAD

**Issue by as-cii** [peterjohnhunt/wordpress-suite#4]
As of Atom 1.14, any method named `initialize` on the main module of a package will be automatically invoked by Atom before calling `activate`. You can read more about the change in this [pull request to Atom's documentation](https://github.com/atom/flight-manual.atom.io/pull/300/files).

Since your package's `initialize` method wasn't written with this behavior in mind, we recommend renaming it to avoid unexpected breakage.

Atom 1.14 should reach the beta channel in early January 2017 and will be on stable in early February 2017. Please rename `initialize` before then to prevent issues, and let us know if you have any questions.

Thanks for your contributions to the Atom community! :bow:

/cc: @peterjohnhunt

**Comment by peterjohnhunt** [comment]
This has been fixed in [v0.4.3](https://github.com/peterjohnhunt/wordpress-suite/releases/tag/v0.4.3).

Thanks!
