### ISSUE TITLE
Package initialisation conditions

### ISSUE THREAD

**Issue by Gaffen** [peterjohnhunt/wordpress-suite#5]
Hi there,

I recently changed my directory structure for wordpress projects, which means there now is now `wp-content` folder in the root of my project.

After a little poking around I realised that this was causing wordpress-suite not to initialise. I was wondering if the conditions to activate the plugin could be updated? I was thinking another indicator that the current project is wordpress would be the presence of `wp-cli.yml` in the root folder. Would this be something worth considering? If not I would appreciate an alternative suggestion.

Really enjoying the plugin!

**Comment by peterjohnhunt** [comment]
Hi @Gaffen,

I am actually just about to release a refactored version where this is already added, along with a ton more wp cli commands and integrations. Just need to polish it up and bug test it. However, i have gone ahead and added this in v0.4.5(https://github.com/peterjohnhunt/wordpress-suite/releases/tag/v0.4.5).

It will now check for a wp-cli.yml in the root folder, and then will initialize as a wordpress site based off that. I'm going to close this, but feel free to reopen it if you run into any issues with the additions!

Thanks for using Wordpress Suite!
