### ISSUE TITLE
capital_p_dangit()

### ISSUE THREAD

**Issue by mckernanin** [peterjohnhunt/wordpress-suite#8]
Kinda nitpicky, but WordPress should always have a capital P. I'd be happy to submit a pull request if you're willing to merge it!

**Comment by peterjohnhunt** [comment]
Hi @mckernanin, hope you're finding wordpress-suite helpful!

Are you referring to the readme specifically? Or some notification? Just wanted to be clear on where you are suggesting the change.

**Comment by mckernanin** [comment]
Setting up a new macbook and just found this plugin, so I'm playing around with it. I noticed in the right click in the tree in Atom, and in the readme.

**Comment by peterjohnhunt** [comment]
Thanks for the clarification! I'm close to releasing v2.0 with much more WP-CLI integration, and will include the letter casing change in that.

Thanks for your contribution!
